version: 1.0.{build}
image: Visual Studio 2019
configuration: Debug
before_build:
- cmd: dotnet restore CSProlog.sln
build:
  project: CSProlog.sln
test_script:
- cmd: >-
    cd .\CSProlog.Core.Test

    dotnet test